name: my_eye
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  google_sign_in: ^5.2.4
  cloud_firestore: ^3.1.11
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  uuid:
  animations: ^2.0.2
  font_awesome_flutter: ^10.1.0
  awesome_notifications: ^0.6.21
  timezone: ^0.8.0
  matrix4_transform: ^2.0.1
  flutter_svg: ^1.0.3
  flutter_staggered_grid_view: ^0.4.0
  firebase_storage: any
  image_picker: ^0.8.3
  clipboard: ^0.1.2+8
  url_launcher:
  avatar_glow: ^2.0.2
  speech_to_text: ^5.4.3
  smooth_page_indicator: ^1.0.0+2
  animated_splash_screen: ^1.1.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13
  flutter_accessibility_service: ^0.0.2
  path: ^1.8.0
  sqflite: ^2.0.0+4
  provider: ^6.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.jpeg"
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/countries/

