// ignore_for_file: override_on_non_overriding_member

import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "Checkout": "الدفع",
          "First Name": "الاسم الأول",
          "Last Name": "الاسم الأخير",
          "Email Address": "البريد الإلكتروني",
          "Phone Number": "رقم هاتف",
          "Tourist App": "البرنامج السياحي",
          "Settings": "إعدادات",
          "Languages": "اللغات",
          "My Trip": "رحلتي",
          "Logout": "تسجيل الخروج",
          "Are you sure you want to log out ?":
              "هل أنت متأكد من أنك تريد تسجيل الخروج ؟",
          "Your data are already saved so when logging back your data will be there.":
              "تم حفظ بياناتك بالفعل، لذا عند تسجيل العودة، ستكون بياناتك موجودة.",
          "Log Out": "تسجيل الخروج",
          "Cancel": "الغاء",
          "Number": "رقم",
          "Expired Date": "التاريخ المنتهي",
          "Card Holder": "حامل بطاقة",
          "Confirmation": "تأكيد",
          "Flight Confirmation": "تأكيد الرحلة",
          "The Start Date": "تاريخ البدء",
          "The End Date": "تاريخ الانتهاء",
          "Adult  (1 - 10)": "للبالغين (1-10)",
          "Child   (1 - 10)": "طفل (1-10)",
          "Mobile Ticket": "تذكرة الهاتف",
          "Check Availability": "التحقق من الصلاحية",
          "Confirm": "تأكيد",
          "Adults": "البالغين",
          "Childern": "الاطفال",
          "Total price": "السعر الكلي",
          "Zoom": "تكبير",
          "default": "إفتراضي",
          "Zoom out": "تصغير",
          "Price": "التكلفة",
          "Tour Type": "نوع الرحلة",
          "Daily Tour": "رحلة يومية",
          "Duration": "مدة الرحلة",
          "OverView for trip": "نظرة عامة للرحلة",
          "Itinerary": "مسار الرحلة",
          "Include": "تضضمن",
          "Exclude": "استبعاد",
          "You have add this trip": "لقد أضفت هذه الرحلة",
          "Join Trip": "الانضمام إلى الرحلة",
          "Usability": "سهولة الاستخدام",
          "The application is very easy to use and if you need help, we are at your service for 24 hours and all transactions through the application by using your voice":
              "التطبيق سهل الاستخدام للغاية وإذا احتجت إلى مساعدة فنحن في خدمتك لمدة 24 ساعة وجميع المعاملات من خلال التطبيق باستخدام صوتك",
          "Let's begin": "هيا نبدأ",
          "From anywhere": "من اي مكان",
          "Book your flight while you are in your home or anywhere":
              "احجز رحلتك وأنت في منزلك أو في أي مكان",
          "Security and safety. Be assured, we are with you":
              "الأمن والسلامة. كن مطمئنا ، نحن معك",
          "We will guarantee your safety and security throughout the trip and throughout your use of the application":
              "سوف نضمن سلامتك وأمنك طوال الرحلة وطوال فترة استخدامك للتطبيق",
          "For free": "مجانا",
          "The application is free for the first time user and this is for a limited period":
              "التطبيق مجاني لأول مرة للمستخدم وهذا لفترة محدودة",
          "Welcome": "مرحبا",
          "The company of your eyes welcomes you": "شركة your eyes ترحب بيكم",
          "Next": "التالي",
          "Sign In": "تسجيل الدخول",
          "Password": "كلمة المرور",
          "Tourism App": "تطبيق السياحة",
          "Sign in with\nadmin": "تسجيل بواسطة\n المسئول",
          "Sign in with\nGoogle": "تسجيل بواسطة \nGoogle",
          "Don't have an account ?": "ليس لديك حساب ؟",
          "Register": "قم بالتسجيل",
          "Sign Up": "اشتراك",
          "Register Now !!": "سجل الان !!",
          "UserName": "اسم االمستخدم",
          "Appearnace": "المظهر",
          "Use device setting": "استخدم إعدادات الجهاز",
          "Auttomatically swtich between Light and Dark themes when your system does":
              "التبديل تلقائيًا بين السمات الفاتحة والداكنة عندما يقوم نظامك بذلك",
          "Light Mode": "وضع الضوء",
          "Dark Mode": "الوضع الداكن",
          "Your purchase has been completed successfully. Thank you for using the app Eye":
              "لقد اتمت عملية الشراء بنجاح شكرا لاستخدمك تطبيق Eye",
          "Skip": "تخطى",
          "First Time": "اول مرة",
          "Is the your first time to use this app ?":
              "هل هذه أول مرة تستخدم فيها هذا التطبيق ؟",
          "Not my First Time": "ليست المرة الأولى",
          "I have use this app several Time !!":
              "لقد استخدمت هذا التطبيق عدة مرات !!",
          "Search": "البحث",
          "Tourist guide": "المرشد السياحي",
          "English": "اللغه الانجليزية",
          "Arabic": "اللغة العربية",
          "Hindi": "اللغه الهندية",
          "Spanish": "اللغه الاسبانية",
          "French": "اللغه الفرنسية",
          "Russian": "اللغه الروسية",
          "Font Controller": "التحكم في الخط",
          "Choice": "اختار",
          "Request Permission !": "طلب إذن !",
          "For mobile, screen readers (TalkBack, VoiceOver) enable visually impaired users to get spoken feedback about the contents of the screen and interact with the UI via gestures on mobile and keyboard shortcuts on desktop. Turn on VoiceOver or TalkBack on your mobile device and navigate around your app.":
              "بالنسبة إلى الأجهزة المحمولة ، تتيح برامج قراءة الشاشة (TalkBack و VoiceOver) للمستخدمين ضعاف البصر الحصول على تعليقات منطوقة حول محتويات الشاشة والتفاعل مع واجهة المستخدم عبر الإيماءات على اختصارات لوحة المفاتيح والجوال على سطح المكتب. قم بتشغيل VoiceOver أو TalkBack على جهازك المحمول وتصفح التطبيق الخاص بك.",
          "Go": "انطلق",
          "No TalkBack": "بدون الخاصية",
          "Choose the language of the application": "اختيار لغه التطبيق",
          "With permision": "بالخاصية",
          "Without permision": "بدوت الخاصية",
          "You have choice": "لقد اخترت",
          "Error choice you have to choice": "خطأ لابد من اختيار الاختيارات",
          "Error!!": "خطأ !!!",
          "Permision": "اذنونات",
          "If you want to cancel a feature (TalkBack, VoiceOver) or want to activate a feature (TalkBack, VoiceOver)":
              "(TalkBack, VoiceOver) اذا كنت تريد الغاء خاصية (TalkBack, VoiceOver) او تريد تفعيل خاصية",
          "Credit Card Details": "تفاصيل بطاقة الائتمان",
          "Name on Card": "الاسم على البطاقة",
          "Card Number": "رقم البطاقة",
          "Card Expiration": "انتهاء بطاقة",
          "Please Order": "من فضلك اطلب",
          "Select Country": "حدد الدولة",
          "Not Yet": "ليس بعد",
          "Please complete all fields": "يرجي اكمال جميع الخانات",
          "Error creating account": "خطأ في إنشاء الحساب",
          "You must enter the data correctly":
              "يجب عليك ادخال البيانات بطريقة صحيحة",
          "Error logging in": "خطأ في تسجيل الدخول",
          "Email or password wrong": "البريد الالكترونى او كلمة السر خطأ",
          "Error signing out": "خطأ في تسجيل الخروج",
          "Internet connection error": "خطأ في اتصال الانترنت",
        },
        "en": {
          "Checkout": "Checkout",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Email Address": "Email Address",
          "Phone Number": "Phone Number",
          "Tourist App": "Tourist App",
          "Settings": "Settings",
          "Languages": "Languages",
          "My Trip": "My Trip",
          "Logout": "0",
          "Are you sure you want to log out ?":
              "Are you sure you want to log out ?",
          "Your data are already saved so when logging back your data will be there.":
              "Your data are already saved so when logging back your data will be there.",
          "Log Out": "Log Out",
          "Cancel": "Cancel",
          "Number": "Number",
          "Expired Date": "Expired Date",
          "Card Holder": "Card Holder",
          "Confirmation": "Confirmation",
          "Flight Confirmation": "Flight Confirmation",
          "The Start Date": "The Start Date",
          "The End Date": "The End Date",
          "Adult  (1 - 10)": "Adult  (1 - 10)",
          "Child   (1 - 10)": "Child   (1 - 10)",
          "Mobile Ticket": "Mobile Ticket",
          "Check Availability": "Check Availability",
          "Confirm": "Confirm",
          "Adults": "Adults",
          "Childern": "Childern",
          "Total price": "Total price",
          "Zoom": "Zoom",
          "default": "default",
          "Zoom out": "Zoom out",
          "Price": "Price",
          "Tour Type": "Tour Type",
          "Daily Tour": "Daily Tour",
          "Duration": "Duration",
          "OverView for trip": "OverView for trip",
          "Itinerary": "Itinerary",
          "Include": "Include",
          "Exclude": "Exclude",
          "You have add this trip": "You have add this trip",
          "Join Trip": "Join Trip",
          "Usability": "Usability",
          "The application is very easy to use and if you need help, we are at your service for 24 hours and all transactions through the application by using your voice":
              "The application is very easy to use and if you need help, we are at your service for 24 hours and all transactions through the application by using your voice",
          "Let's begin": "Let's begin",
          "From anywhere": "From anywhere",
          "Book your flight while you are in your home or anywhere":
              "Book your flight while you are in your home or anywhere",
          "Security and safety. Be assured, we are with you":
              "Security and safety. Be assured, we are with you",
          "We will guarantee your safety and security throughout the trip and throughout your use of the application":
              "We will guarantee your safety and security throughout the trip and throughout your use of the application",
          "For free": "For free",
          "The application is free for the first time user and this is for a limited period":
              "The application is free for the first time user and this is for a limited period",
          "Welcome": "Welcome",
          "The company of your eyes welcomes you":
              "The company of your eyes welcomes you",
          "Next": "Next",
          "Sign In": "Sign In",
          "Password": "Password",
          "Tourism App": "Tourism App",
          "Sign in with\nadmin": "Sign in with\nadmin",
          "Sign in with\nGoogle": "Sign in with\nGoogle",
          "Don't have an account ?": "Don't have an account ?",
          "Register": "Register",
          "Sign Up": "Sign Up",
          "Register Now !!": "Register Now !!",
          "UserName": "UserName",
          "Appearnace": "Appearnace",
          "Use device setting": "Use device setting",
          "Auttomatically swtich between Light and Dark themes when your system does":
              "Auttomatically swtich between Light and Dark themes when your system does",
          "Light Mode": "Light Mode",
          "Dark Mode": "Dark Mode",
          "Your purchase has been completed successfully. Thank you for using the app Eye":
              "Your purchase has been completed successfully. Thank you for using the app Eye",
          "Skip": "Skip",
          "First Time": "First Time",
          "Is the your first time to use this app ?":
              "Is the your first time to use this app ?",
          "Not my First Time": "Not my First Time",
          "I have use this app several Time !!":
              "I have use this app several Time !!",
          "Search": "Search",
          "Tourist guide": "Tourist guide",
          "English": "English",
          "Arabic": "Arabic",
          "Hindi": "Hindi",
          "Spanish": "Spanish",
          "French": "French",
          "Russian": "Russian",
          "Font Controller": "Font Controller",
          "Choice": "Choice",
          "Request Permission !": "Request Permission !",
          "For mobile, screen readers (TalkBack, VoiceOver) enable visually impaired users to get spoken feedback about the contents of the screen and interact with the UI via gestures on mobile and keyboard shortcuts on desktop. Turn on VoiceOver or TalkBack on your mobile device and navigate around your app.":
              "For mobile, screen readers (TalkBack, VoiceOver) enable visually impaired users to get spoken feedback about the contents of the screen and interact with the UI via gestures on mobile and keyboard shortcuts on desktop. Turn on VoiceOver or TalkBack on your mobile device and navigate around your app.",
          "Go": "Go",
          "No TalkBack": "No TalkBack",
          "Choose the language of the application":
              "Choose the language of the application",
          "With permision": "With permision",
          "Without permision": "Without permision",
          "You have choice": "You have choice",
          "Error choice you have to choice": "Error choice you have to choice",
          "Error!!": "Error!!",
          "Permision": "Permision",
          "If you want to cancel a feature (TalkBack, VoiceOver) or want to activate a feature (TalkBack, VoiceOver)":
              "If you want to cancel a feature (TalkBack, VoiceOver) or want to activate a feature (TalkBack, VoiceOver)",
          "Credit Card Details": "Credit Card Details",
          "Name on Card": "Name on Card",
          "Card Number": "Card Number",
          "Card Expiration": "Card Expiration",
          "Please Order": "Please Order",
          "Select Country": "Select Country",
          "Not Yet": "Not Yet",
          "Please complete all fields": "Please complete all fields",
          "Error creating account": "Error creating account",
          "You must enter the data correctly":
              "You must enter the data correctly",
          "Error logging in": "Error logging in",
          "Email or password wrong": "Email or password wrong",
          "Error signing out": "Error signing out",
          "Internet connection error": "Internet connection error",
        },
      };
}
